import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import axios from 'axios';

const AddEmployeePage = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const employeeToEdit = location.state?.employee; // Access the passed employee data if available

  const [employee, setEmployee] = useState({
    id: null, // Default id value, will be assigned later
    username: '',
    email: '',
    status: 'Active', // Default value
  });

  const [statusOptions] = useState(['Active', 'Inactive']); // Status options for the drop-down

  // If employeeToEdit exists, pre-fill the form
  useEffect(() => {
    if (employeeToEdit) {
      setEmployee(employeeToEdit); // Pre-fill form with employee data
    } else {
      // For new employee, set the ID to a numerical value (can be auto-generated by backend)
      // For now, we assume that the backend will handle ID assignment or increment it here
      setEmployee((prevState) => ({
        ...prevState,
        id: Date.now(), // This generates a unique ID based on timestamp (for demo purposes)
      }));
    }
  }, [employeeToEdit]);

  // Handle form submission (Add or Update Employee)
  const handleSubmit = async (event) => {
    event.preventDefault();

    if (employeeToEdit) {
      // If employeeToEdit exists, update the employee
      try {
        const response = await axios.put(
          `http://localhost:3000/employees/${employeeToEdit.id}`,
          employee
        );
        console.log('Employee updated successfully', response.data);
        navigate('/'); // Redirect to home page after updating
      } catch (error) {
        console.error('Error updating employee:', error);
      }
    } else {
      // If no employeeToEdit, create a new employee
      try {
        const response = await axios.post('http://localhost:3000/employees', employee);
        console.log('Employee added successfully', response.data);
        navigate('/'); // Redirect to home page after adding
      } catch (error) {
        console.error('Error adding employee:', error);
      }
    }
  };

  return (
    <div>
      <h1>{employeeToEdit ? 'Edit Employee' : 'Add Employee'}</h1>
      <form onSubmit={handleSubmit}>
        <div>
          <label>Username:</label>
          <input
            type="text"
            value={employee.username}
            onChange={(e) => setEmployee({ ...employee, username: e.target.value })}
          />
        </div>
        <div>
          <label>Email:</label>
          <input
            type="email"
            value={employee.email}
            onChange={(e) => setEmployee({ ...employee, email: e.target.value })}
          />
        </div>
        <div>
          <label>Status:</label>
          <select
            value={employee.status}
            onChange={(e) => setEmployee({ ...employee, status: e.target.value })}
          >
            {statusOptions.map((status) => (
              <option key={status} value={status}>
                {status}
              </option>
            ))}
          </select>
        </div>
        <button type="submit">{employeeToEdit ? 'Update Employee' : 'Add Employee'}</button>
      </form>
    </div>
  );
};

export default AddEmployeePage;
